### PR TITLE
change entrance and submitted text for timex-exam

### PR DESCRIPTION
**Pull request by wajeeha-khalid**
change entrance and submitted text for timex-exam

### CODE REVIEW

**Comment by wajeeha-khalid** [comment]
@amir-qayyum-khan fyi; I am going to merge this PR to release branch and will refer release branch to link with edx-platform as github egg reference

**Comment by amir-qayyum-khan** [comment]
progress btn is hidden on exam end?

**Comment by wajeeha-khalid** [comment]
which progress button?

**Comment by wajeeha-khalid** [comment]
Yes, it is hidden. Going to merge PR

**Pull request merged**
